order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /
cart:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /

delivery:
    resource: "@DeliveryBundle/Resources/config/routing.yml"
    prefix:   /

sav:
    resource: "@SavBundle/Resources/config/routing.yml"
    prefix:   /Sav

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

marketing_front:
    prefix:     /marketing_front
    resource: "@MarketingBundle/Resources/config/routing/Front.yml"
marketing_back:
    prefix:     /marketing_back
    resource: "@MarketingBundle/Resources/config/routing/Back.yml"

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    path: /connect/check-facebook
google_login:
    path: /login/check-google
app:
    resource: '@AppBundle/Controller/'
    type: annotation


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /